export const DARK_MAP_STYLE = [
  { elementType: 'geometry', stylers: [{ color: '#171614' }] },
  { elementType: 'labels.icon', stylers: [{ saturation: -35 }, { lightness: -15 }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#D6D0C5' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#171614' }, { weight: 2 }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ color: '#5E5A52' }] },
  {
    featureType: 'administrative.country',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#E0D8C9' }],
  },
  { featureType: 'administrative.land_parcel', stylers: [{ visibility: 'off' }] },
  {
    featureType: 'administrative.locality',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#F0E6D6' }],
  },
  { featureType: 'poi', elementType: 'geometry', stylers: [{ color: '#221F1A' }] },
  { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#B9AF9F' }] },
  { featureType: 'poi.business', elementType: 'labels.text.fill', stylers: [{ color: '#D8B06A' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#163423' }] },
  {
    featureType: 'poi.park',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#8FBF8E' }],
  },
  {
    featureType: 'poi.park',
    elementType: 'labels.text.stroke',
    stylers: [{ color: '#102417' }],
  },
  { featureType: 'road', elementType: 'geometry.fill', stylers: [{ color: '#4A3524' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#1E1914' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#CDBA9B' }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ color: '#6B4A2E' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#8A6238' }] },
  {
    featureType: 'road.highway.controlled_access',
    elementType: 'geometry',
    stylers: [{ color: '#A87942' }],
  },
  {
    featureType: 'road.local',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#A89B89' }],
  },
  { featureType: 'transit', elementType: 'geometry', stylers: [{ color: '#243040' }] },
  { featureType: 'transit', elementType: 'labels.text.fill', stylers: [{ color: '#9CB4CF' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#102A3A' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#79A8C7' }] },
]
