import { StyleSheet } from 'react-native'
import { radius } from '@/constants/Radius'
import { spacing } from '@/constants/Spacing'
import { fontSize, fontWeight, letterSpacing, lineHeight } from '@/constants/Typography'
import type { useThemeColors } from '@/lib/contexts/ThemeContext'

export function makeStyles(c: ReturnType<typeof useThemeColors>) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: c.bg },
    header: {
      height: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing[4],
      borderBottomWidth: 0.5,
      borderBottomColor: c.border,
    },
    backBtn: { flexDirection: 'row', alignItems: 'center', gap: spacing[1], padding: spacing.px6, marginLeft: -spacing.px6 },
    backText: { fontSize: fontSize.md, color: c.text2 },
    headerActions: { flexDirection: 'row', gap: spacing.px6 },
    loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    photoPlaceholder: {
      height: 220,
      backgroundColor: c.surface,
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing[2],
    },
    absoluteFill: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
    photoPlaceholderText: { fontSize: fontSize.bodySm, color: c.text3 },
    infoSection: { paddingHorizontal: spacing[5], paddingTop: spacing.px18, paddingBottom: spacing[2] },
    placeName: { fontSize: fontSize['3xl'], fontWeight: fontWeight.bold, color: c.text, marginBottom: spacing.px6 },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.px6,
      marginBottom: spacing[4],
      flexWrap: 'wrap',
    },
    metaText: { fontSize: fontSize.bodySm, color: c.text3 },
    metaDot: { fontSize: fontSize.bodySm, color: c.text3 },
    improveButton: {
      alignSelf: 'flex-start',
      borderWidth: 0.5,
      borderColor: c.border,
      backgroundColor: c.surface,
      borderRadius: radius.lg,
      paddingHorizontal: spacing[3],
      paddingVertical: spacing[2],
      marginBottom: spacing.px14,
    },
    improveButtonText: { fontSize: fontSize.bodySm, fontWeight: fontWeight.semibold, color: c.text2 },
    ratingsCard: {
      backgroundColor: c.surface,
      borderRadius: radius.md3,
      marginBottom: spacing[5],
      overflow: 'hidden',
    },
    ratingsCardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: spacing.px14,
      paddingVertical: spacing[3],
      gap: spacing[3],
    },
    ratingsCardLabel: { fontSize: fontSize.sm, fontWeight: fontWeight.semibold, color: c.text3, width: 52 },
    ratingsCardValues: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.px6,
      flexWrap: 'wrap',
    },
    ratingsCardDivider: { height: 0.5, backgroundColor: c.border, marginHorizontal: spacing.px14 },
    ratingEmoji: { fontSize: fontSize.md },
    ratingValue: { fontSize: fontSize.lg, fontWeight: fontWeight.bold, color: c.text },
    ratingCount: { fontSize: fontSize.sm, color: c.text3, marginLeft: spacing.px2 },
    ratingChip: { flexDirection: 'row', alignItems: 'center', gap: spacing.px2 },
    ratingChipLabel: { fontSize: fontSize['2xs'], color: c.text3, letterSpacing: letterSpacing.wide, marginRight: spacing.px2 },
    recentReviewsNote: {
      fontSize: fontSize.xs,
      color: c.text3,
      paddingHorizontal: spacing.px14,
      paddingBottom: spacing[2],
      fontStyle: 'italic',
    },
    dishMentions: { flex: 1, fontSize: fontSize.bodySm, color: c.text2 },
    dishMentionRow: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] },
    dishMentionChip: { minHeight: 44 },
    dishesSection: { paddingHorizontal: spacing[5], paddingTop: spacing[4], paddingBottom: spacing[3] },
    dishesSectionTitle: { fontSize: fontSize.base, fontWeight: fontWeight.semibold, color: c.text, marginBottom: spacing.px10 },
    dishesRow: { gap: spacing[2] },
    dishChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.px5,
      backgroundColor: c.surface,
      borderRadius: radius.pill,
      paddingHorizontal: spacing[3],
      paddingVertical: spacing.px6,
      borderWidth: 0.5,
      borderColor: c.border,
    },
    dishChipName: { fontSize: fontSize.bodySm, fontWeight: fontWeight.medium, color: c.text },
    dishChipCount: {
      fontSize: fontSize.xs,
      color: c.text3,
      backgroundColor: c.surface2,
      borderRadius: radius.sm3,
      paddingHorizontal: spacing.px5,
      paddingVertical: spacing.px1,
    },
    divider: { height: 0.5, backgroundColor: c.border },
    contactSection: { paddingVertical: spacing[1] },
    contactRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing[3], paddingVertical: spacing.px11 },
    contactText: { flex: 1, fontSize: fontSize.base, color: c.text2, lineHeight: lineHeight.body },
    contactTextBold: { fontWeight: fontWeight.semibold, color: c.text },
    contactTextLink: { flex: 1, fontSize: fontSize.base, color: c.info, lineHeight: lineHeight.body },
    postsSection: { paddingTop: spacing[4], paddingBottom: spacing[1] },
    postsSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing[5],
      marginBottom: spacing[3],
    },
    postsSectionTitle: { fontSize: fontSize.base, fontWeight: fontWeight.semibold, color: c.text },
    sortBtn: { flexDirection: 'row', alignItems: 'center', gap: spacing[1] },
    sortBtnText: { fontSize: fontSize.bodySm, color: c.text2 },
    emptyPostsText: { fontSize: fontSize.base, color: c.text3, paddingHorizontal: spacing[5], paddingVertical: spacing[2] },
    postRow: {
      flexDirection: 'row',
      gap: spacing[3],
      paddingHorizontal: spacing[5],
      paddingVertical: spacing[3],
      borderBottomWidth: 0.5,
      borderBottomColor: c.border,
    },
    postThumb: {
      width: 60,
      height: 60,
      borderRadius: radius.sm3,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    postRowContent: { flex: 1, gap: spacing.px3 },
    postRowTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    postRowCreator: { fontSize: fontSize.sm, color: c.text3 },
    postRowLikes: { fontSize: fontSize.sm, color: c.text3 },
    postRowTitle: { fontSize: fontSize.base, color: c.text, lineHeight: lineHeight.small },
    sheetBackdrop: { flex: 1, backgroundColor: c.overlay },
    sheet: {
      backgroundColor: c.bg,
      borderTopLeftRadius: radius.pill,
      borderTopRightRadius: radius.pill,
      borderTopWidth: 0.5,
      borderTopColor: c.border,
      paddingHorizontal: spacing[6],
      paddingTop: spacing.px14,
      paddingBottom: spacing.px40,
      alignItems: 'center',
      gap: spacing.px10,
    },
    sheetHandle: {
      width: 36,
      height: 4,
      borderRadius: radius.xxs,
      backgroundColor: c.border2,
      marginBottom: spacing.px6,
    },
    sheetIcon: {
      width: 48,
      height: 48,
      borderRadius: radius.pill3,
      backgroundColor: c.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: spacing.px2,
    },
    sheetTitle: { fontSize: fontSize.title, fontWeight: fontWeight.semibold, color: c.text },
    sheetBody: { fontSize: fontSize.base, color: c.text2, textAlign: 'center', lineHeight: lineHeight.body },
    sheetBtnPrimary: {
      width: '100%',
      backgroundColor: c.text,
      borderRadius: radius.lg,
      paddingVertical: spacing.px14,
      alignItems: 'center',
      marginTop: spacing.px6,
    },
    sheetBtnPrimaryText: { fontSize: fontSize.md, fontWeight: fontWeight.semibold, color: c.bg },
    sheetBtnSecondary: {
      width: '100%',
      backgroundColor: c.surface,
      borderWidth: 0.5,
      borderColor: c.border2,
      borderRadius: radius.lg,
      paddingVertical: spacing.px14,
      alignItems: 'center',
    },
    sheetBtnSecondaryText: { fontSize: fontSize.md, fontWeight: fontWeight.medium, color: c.text },
  })
}
