import { StyleSheet } from 'react-native'
import { elevation } from '@/constants/Elevation'
import { radius } from '@/constants/Radius'
import { spacing } from '@/constants/Spacing'
import { fontSize, fontWeight, lineHeight } from '@/constants/Typography'
import type { useThemeColors } from '@/lib/contexts/ThemeContext'

export function makeStyles(c: ReturnType<typeof useThemeColors>) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: c.bg },
    topBar: {
      height: 56,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing[4],
      borderBottomWidth: 0.5,
      borderBottomColor: c.border,
    },
    backToSaved: {
      position: 'absolute',
      left: spacing[3],
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing[1],
    },
    backToSavedText: { fontSize: fontSize.md, color: c.text2 },
    backToSavedSpacer: { position: 'absolute', right: spacing[4], width: 60 },
    title: { fontSize: fontSize.lg, fontWeight: fontWeight.medium, color: c.text },
    content: { flex: 1 },
    toggleRow: {
      flexDirection: 'row',
      backgroundColor: c.surface,
      borderRadius: radius.sm3,
      margin: spacing[4],
      marginBottom: spacing[0],
      padding: spacing.px3,
      gap: spacing.px3,
    },
    toggleBtn: { flex: 1, paddingVertical: spacing.px6, borderRadius: radius.sm, alignItems: 'center' },
    toggleBtnActive: { backgroundColor: c.bg },
    toggleText: { fontSize: fontSize.bodySm, fontWeight: fontWeight.medium, color: c.text3 },
    toggleTextActive: { color: c.text },
    filterRow: {
      alignItems: 'center',
      paddingHorizontal: spacing[4],
      paddingVertical: spacing[2],
      gap: spacing[2],
    },
    filterScroll: {
      flexGrow: 0,
      flexShrink: 0,
      height: 52,
      borderBottomWidth: 0.5,
      borderBottomColor: c.border,
    },
    viewsContainer: { flex: 1 },
    sortHeader: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      paddingHorizontal: spacing[4],
      paddingVertical: spacing.px10,
      borderBottomWidth: 0.5,
      borderBottomColor: c.border,
    },
    sortBtn: { flexDirection: 'row', alignItems: 'center', gap: spacing.px5 },
    sortBtnText: { fontSize: fontSize.bodySm, color: c.text2 },
    letterHeader: { paddingHorizontal: spacing[4], paddingVertical: spacing.px6, backgroundColor: c.surface },
    letterText: { fontSize: fontSize.sm, fontWeight: fontWeight.semibold, color: c.text3 },
    visitBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginHorizontal: spacing[4],
      marginTop: spacing[3],
      marginBottom: spacing[1],
      backgroundColor: c.surface,
      borderRadius: radius.md3,
      borderWidth: 0.5,
      borderColor: c.border,
      paddingHorizontal: spacing.px14,
      paddingVertical: spacing[3],
    },
    visitBannerText: { flex: 1 },
    visitBannerTitle: { fontSize: fontSize.base, fontWeight: fontWeight.semibold, color: c.text, marginBottom: spacing.px2 },
    visitBannerSub: { fontSize: fontSize.sm, color: c.accent },
    visitBannerClose: { paddingLeft: spacing.px10 },
    visitBannerCloseText: { fontSize: fontSize.bodySm, color: c.text3 },
    placeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing[3],
      paddingHorizontal: spacing[4],
      paddingVertical: spacing[3],
      borderBottomWidth: 0.5,
      borderBottomColor: c.border,
    },
    placeRowName: { fontSize: fontSize.base, fontWeight: fontWeight.medium, color: c.text, marginBottom: spacing.px2 },
    placeRowAddress: { fontSize: fontSize.sm, color: c.text3 },
    locationCard: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: c.bg,
      borderTopLeftRadius: radius.lg2,
      borderTopRightRadius: radius.lg2,
      borderTopWidth: 0.5,
      borderTopColor: c.border,
      paddingHorizontal: spacing[5],
      paddingTop: spacing[3],
      paddingBottom: spacing[8],
      gap: spacing[1],
      ...elevation.sm,
    },
    cardHandle: {
      width: 36,
      height: 4,
      borderRadius: radius.xxs,
      backgroundColor: c.border2,
      alignSelf: 'center',
      marginBottom: spacing.px10,
    },
    cardPhoto: { width: '100%', height: 130, borderRadius: radius.md, marginBottom: spacing[1] },
    cardName: { fontSize: fontSize.xl, fontWeight: fontWeight.semibold, color: c.text },
    cardMeta: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] },
    cardMetaText: { fontSize: fontSize.base, color: c.text2 },
    cardHours: { fontSize: fontSize.bodySm, color: c.text3 },
    cardPhoneRow: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] },
    cardPhoneText: { fontSize: fontSize.bodySm, color: c.text2 },
    cardActions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.px10, marginTop: spacing[1] },
    cardBtnPrimary: {
      flexGrow: 1,
      minWidth: 128,
      borderRadius: radius.pill,
      backgroundColor: c.text,
      paddingVertical: spacing.px11,
      alignItems: 'center',
    },
    cardBtnPrimaryText: { fontSize: fontSize.base, fontWeight: fontWeight.medium, color: c.bg },
    cardBtnSecondary: {
      flexGrow: 1,
      minWidth: 112,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: c.border2,
      paddingVertical: spacing.px11,
      alignItems: 'center',
    },
    cardBtnSecondaryText: { fontSize: fontSize.base, fontWeight: fontWeight.medium, color: c.text },
    locateBtn: {
      position: 'absolute',
      right: 16,
      bottom: 116,
      width: 40,
      height: 40,
      borderRadius: radius.md,
      backgroundColor: c.bg,
      alignItems: 'center',
      justifyContent: 'center',
      ...elevation.sm,
    },
    zoomControls: {
      position: 'absolute',
      right: 16,
      bottom: 24,
      backgroundColor: c.bg,
      borderRadius: radius.md,
      overflow: 'hidden',
      ...elevation.sm,
    },
    zoomBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
    zoomBtnText: { fontSize: fontSize['3xl'], fontWeight: fontWeight.light, color: c.text, lineHeight: lineHeight.display },
    zoomDivider: { height: 0.5, backgroundColor: c.border },
  })
}
