import { StyleSheet } from 'react-native'
import { radius } from '@/constants/Radius'
import { spacing } from '@/constants/Spacing'
import { fontSize, fontWeight, lineHeight } from '@/constants/Typography'
import type { useThemeColors } from '@/lib/contexts/ThemeContext'

export function makeStyles(c: ReturnType<typeof useThemeColors>) {
  return StyleSheet.create({
    scroll: { flex: 1 },
    locationSection: { paddingHorizontal: spacing[4], paddingTop: spacing[1], zIndex: 10 },
    searchWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing[2],
      backgroundColor: c.bg,
      borderRadius: radius.md3,
      paddingHorizontal: spacing.px13,
      minHeight: 46,
      borderWidth: 0.5,
      borderColor: c.border,
    },
    fieldFocused: { borderColor: c.accent, backgroundColor: c.bg },
    searchInput: { flex: 1, fontSize: fontSize.lg, color: c.text, padding: spacing[0] },
    locationConfirmed: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.px10,
      backgroundColor: c.bg,
      borderRadius: radius.md3,
      paddingHorizontal: spacing.px13,
      minHeight: 46,
      borderWidth: 0.5,
      borderColor: c.border,
    },
    locationConfirmedText: { flex: 1 },
    locationName: { fontSize: fontSize.md, fontWeight: fontWeight.medium, color: c.text },
    locationAddress: { fontSize: fontSize.sm, color: c.text3, marginTop: spacing.px1 },
    dropdown: {
      backgroundColor: c.bg,
      borderRadius: radius.md3,
      borderWidth: 0.5,
      borderColor: c.border,
      marginTop: spacing[1],
      overflow: 'hidden',
    },
    dropdownItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.px10,
      paddingHorizontal: spacing.px13,
      paddingVertical: spacing.px11,
      borderBottomWidth: 0.5,
      borderBottomColor: c.border,
    },
    dropdownItemText: { flex: 1 },
    dropdownName: { fontSize: fontSize.base, color: c.text, fontWeight: fontWeight.medium },
    dropdownSub: { fontSize: fontSize.sm, color: c.text3, marginTop: spacing.px1 },
    dropdownEmpty: { paddingVertical: spacing[4], alignItems: 'center' },
    dropdownEmptyText: { fontSize: fontSize.bodySm, color: c.text3 },
    nearbyLabel: { fontSize: fontSize.xs, fontWeight: fontWeight.bold, color: c.text3, paddingHorizontal: spacing[3], paddingTop: spacing.px10, paddingBottom: spacing[1] },
    photoEmpty: {
      marginHorizontal: spacing[4],
      marginTop: spacing[2],
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: `${c.accent}55`,
      borderRadius: radius.lg2,
      aspectRatio: 2.2,
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.px10,
      backgroundColor: `${c.accent}08`,
    },
    photoEmptyLabel: { fontSize: fontSize.lg, fontWeight: fontWeight.extrabold, color: c.text2 },
    photoEmptySub: { fontSize: fontSize.bodySm, color: c.text3, textAlign: 'center', paddingHorizontal: spacing.px28 },
    mediaActionRow: { flexDirection: 'row', gap: spacing.px10, marginTop: spacing[1] },
    mediaActionBtn: {
      minHeight: 38,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.px7,
      paddingHorizontal: spacing.px14,
      borderRadius: radius.xl2,
      backgroundColor: `${c.accent}14`,
      borderWidth: 0.5,
      borderColor: `${c.accent}24`,
    },
    mediaActionText: { fontSize: fontSize.base, fontWeight: fontWeight.extrabold, color: c.accent },
    photosSection: { marginTop: spacing.px14 },
    photoActions: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing[4], marginTop: spacing.px10 },
    photoActionBtn: { paddingVertical: spacing[1], paddingHorizontal: spacing.px2 },
    photoActionText: { fontSize: fontSize.bodySm, color: c.text3 },
    photoOnlyHint: { fontSize: fontSize.sm, color: c.text3, paddingHorizontal: spacing[4], paddingTop: spacing[2] },
    dishTagChips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.px6, paddingHorizontal: spacing[4], paddingTop: spacing.px10 },
    dishTagChip: {
      overflow: 'hidden',
      borderRadius: radius.lg,
      backgroundColor: `${c.accent}12`,
      color: c.accent,
      fontSize: fontSize.bodySm,
      fontWeight: fontWeight.semibold,
      paddingHorizontal: spacing.px10,
      paddingVertical: spacing.px5,
    },
    titleSection: { paddingHorizontal: spacing[4], paddingTop: spacing.px10 },
    titleInput: {
      minHeight: 54,
      borderRadius: radius.lg,
      borderWidth: 0.5,
      borderColor: c.border,
      backgroundColor: c.bg,
      paddingHorizontal: spacing.px14,
      paddingVertical: spacing[3],
      fontSize: fontSize.title,
      fontWeight: fontWeight.bold,
      color: c.text,
      lineHeight: lineHeight.titleRelaxed,
    },
    charCount: { fontSize: fontSize.xs, color: c.text3, textAlign: 'right', marginTop: spacing.px5 },
    tagModalContainer: { flex: 1, backgroundColor: c.bg, alignItems: 'center' },
    tagModalHeader: {
      width: '100%',
      height: 56,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing[5],
      borderBottomWidth: 0.5,
      borderBottomColor: c.border,
    },
    tagModalTitle: { fontSize: fontSize.xl, fontWeight: fontWeight.semibold, color: c.text },
    tagModalDone: { padding: spacing[1] },
    tagModalDoneText: { fontSize: fontSize.lg, fontWeight: fontWeight.medium, color: c.accent },
    tagModalHint: {
      fontSize: fontSize.bodySm,
      color: c.text3,
      paddingHorizontal: spacing[5],
      paddingTop: spacing.px14,
      paddingBottom: spacing[1],
      alignSelf: 'flex-start',
    },
    tagPhotoStrip: { gap: spacing[2], paddingHorizontal: spacing[4], paddingVertical: spacing[3] },
    tagPhotoThumb: { width: 52, height: 52, borderRadius: radius.sm3, overflow: 'hidden', borderWidth: 2, borderColor: 'transparent' },
    tagPhotoThumbActive: { borderColor: c.accent },
    tagPhotoThumbImg: { width: '100%', height: '100%' },
    tagPhotoArea: {
      borderRadius: radius.lg,
      overflow: 'hidden',
      backgroundColor: c.surface2,
      position: 'relative',
      marginTop: spacing[2],
    },
    tagHint: {
      position: 'absolute',
      bottom: 10,
      alignSelf: 'center',
      backgroundColor: 'rgba(0,0,0,0.42)', // check:tokens-ignore
      borderRadius: radius.sm3,
      paddingHorizontal: spacing.px10,
      paddingVertical: spacing[1],
    },
    tagHintText: { fontSize: fontSize.sm, color: 'rgba(255,255,255,0.85)' }, // check:tokens-ignore
    tagList: { width: '100%', paddingHorizontal: spacing[5], paddingTop: spacing[4], gap: spacing.px10 },
    tagListItem: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] },
    tagListDot: { width: 6, height: 6, borderRadius: radius.tiny, backgroundColor: c.accent },
    tagListName: { flex: 1, fontSize: fontSize.base, color: c.text },
    dishTagTooltip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.px10,
      marginHorizontal: spacing[4],
      marginTop: spacing.px10,
      backgroundColor: `${c.accent}12`,
      borderRadius: radius.md3,
      paddingHorizontal: spacing.px13,
      paddingVertical: spacing.px10,
      borderWidth: 0.5,
      borderColor: `${c.accent}24`,
    },
    dishTagTooltipText: {
      flex: 1,
      fontSize: fontSize.bodySm,
      color: c.text2,
    },
    dishTagTooltipDismiss: {
      minWidth: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
  })
}
