-- Semantic search via pgvector + Supabase built-in gte-small embeddings (free, 384 dims)
-- Embeddings generated by supabase/functions/embed-content Edge Function

create extension if not exists vector with schema extensions;

-- Add embedding columns (nullable — populated async after post/restaurant creation)
alter table public.posts
  add column if not exists embedding extensions.vector(384);

alter table public.restaurants
  add column if not exists embedding extensions.vector(384);

-- HNSW indexes — faster than IVFFlat at this scale, self-tunes
create index if not exists posts_embedding_idx
  on public.posts using hnsw (embedding extensions.vector_cosine_ops)
  where embedding is not null;

create index if not exists restaurants_embedding_idx
  on public.restaurants using hnsw (embedding extensions.vector_cosine_ops)
  where embedding is not null;

-- match_embeddings: called by Edge Function / useSearch when FTS returns < 5 results
create or replace function public.match_embeddings(
  query_embedding extensions.vector(384),
  match_type text,
  match_count integer default 10,
  similarity_threshold real default 0.65
)
returns table (id uuid, similarity real)
language plpgsql stable as $$
begin
  if match_type = 'post' then
    return query
      select p.id, (1 - (p.embedding <=> query_embedding))::real as similarity
      from public.posts p
      where p.embedding is not null
        and p.deleted_at is null
        and (1 - (p.embedding <=> query_embedding)) > similarity_threshold
      order by similarity desc
      limit match_count;
  elsif match_type = 'restaurant' then
    return query
      select r.id, (1 - (r.embedding <=> query_embedding))::real as similarity
      from public.restaurants r
      where r.embedding is not null
        and (1 - (r.embedding <=> query_embedding)) > similarity_threshold
      order by similarity desc
      limit match_count;
  end if;
end;
$$;
